# install number library

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# numpy array operation

# import numpy

In [2]:
import numpy as np

In [3]:
np.version.version

'1.25.2'

# one dimensional array

# 1.syntax: numpy.array([values])

# 2.values: element in the array

 first_array=np.array([1,2,3,4,5])

In [7]:
print(first_array)

[1 2 3 4 5]


# 2D ARRAY

In [9]:
second_array=np.array([(4,5,6),(7,8,9)])
print(second_array)

[[4 5 6]
 [7 8 9]]


# 3D ARRAY

In [10]:
number=np.array([[(10,20,30),(40,50,60),(70,80,90),(25,35,47,)]])
print(number)

[[[10 20 30]
  [40 50 60]
  [70 80 90]
  [25 35 47]]]


# array of zero
#creating array with zero

In [11]:
num=np.array(0)
print(num)

0


In [13]:
num1=np.zeros((4,4))
print(num1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
num1=np.ones((4,4))
print(num1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
abi=np.linspace(1,50,100)
print(abi)

[ 1.          1.49494949  1.98989899  2.48484848  2.97979798  3.47474747
  3.96969697  4.46464646  4.95959596  5.45454545  5.94949495  6.44444444
  6.93939394  7.43434343  7.92929293  8.42424242  8.91919192  9.41414141
  9.90909091 10.4040404  10.8989899  11.39393939 11.88888889 12.38383838
 12.87878788 13.37373737 13.86868687 14.36363636 14.85858586 15.35353535
 15.84848485 16.34343434 16.83838384 17.33333333 17.82828283 18.32323232
 18.81818182 19.31313131 19.80808081 20.3030303  20.7979798  21.29292929
 21.78787879 22.28282828 22.77777778 23.27272727 23.76767677 24.26262626
 24.75757576 25.25252525 25.74747475 26.24242424 26.73737374 27.23232323
 27.72727273 28.22222222 28.71717172 29.21212121 29.70707071 30.2020202
 30.6969697  31.19191919 31.68686869 32.18181818 32.67676768 33.17171717
 33.66666667 34.16161616 34.65656566 35.15151515 35.64646465 36.14141414
 36.63636364 37.13131313 37.62626263 38.12121212 38.61616162 39.11111111
 39.60606061 40.1010101  40.5959596  41.09090909 41.

In [30]:
subash=np.ones([2,2])
print(subash)

[[1. 1.]
 [1. 1.]]


In [25]:
kani=np.array([(20,40),(70,60)])
print(kani)

[[20 40]
 [70 60]]


In [27]:
abi=np.array([(80,4,6),(79,67,33),(55,88,62)])
print(abi)

[[80  4  6]
 [79 67 33]
 [55 88 62]]


# definition ***transpose interchange the row and coloums

In [32]:
matrix_transpose=np.transpose(kani)
print(matrix_transpose)

[[20 70]
 [40 60]]


# ravel using a single dimensional array

In [33]:
matrix_transpose.ravel()

array([20, 70, 40, 60])

# reshape is change values in the list

In [46]:
subash.reshape(2,2)

array([[1., 1.],
       [1., 1.]])

In [40]:
abi.reshape(1,9)

array([[80,  4,  6, 79, 67, 33, 55, 88, 62]])

In [47]:
np.random.random((3,3))

array([[0.62860083, 0.74337559, 0.12269547],
       [0.01170744, 0.40748036, 0.74019765],
       [0.30105242, 0.40422679, 0.5351076 ]])